checksumBehavior: update

nodeLinker: node-modules

npmScopes:
  collabsoft-net:
    npmAuthToken: "${NPM_TOKEN-}"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
